<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DateTimeZone;
use DateTime;
use Exception;

class TimeController extends Controller
{
    public function index()
    {
        // Certifique-se de que o nome da view está correto
        return view('time');
    }

    public function getTime(Request $request)
    {

        $country = $request->input('country');
        
        // Aqui você deve ter a lógica para converter o nome do país para o fuso horário correspondente
        $capitals = [
            'Angola' => 'Africa/Luanda',
            'Argélia' => 'Africa/Algiers',       
            'Benim' => 'Africa/Porto-Novo',
            'Botswana' => 'Africa/Gaborone',
            'Burkina Faso' => 'Africa/Ouagadougou',
            'Burundi' => 'Africa/Bujumbura',
            'Cabo Verde' => 'Atlantic/Cape_Verde',
            'Camarões' => 'Africa/Douala',         
            'Chade' => 'Africa/Ndjamena',          
            'Comores' => 'Indian/Comoro',          
            'Costa do Marfim' => 'Africa/Abidjan', 
            'Djibouti' => 'Africa/Djibouti',
            'Egito' => 'Africa/Cairo',
            'Eritreia' => 'Africa/Asmara',
            'Etiópia' => 'Africa/Addis_Ababa',    
            'Gabão' => 'Africa/Libreville',
            'Gana' => 'Africa/Accra',             
            'Guiné' => 'Africa/Conakry',          
            'Guiné Equatorial' => 'Africa/Malabo',
            'Guiné-Bissau' => 'Africa/Bissau',
            'Gâmbia' => 'Africa/Banjul',
            'Lesoto' => 'Africa/Maseru',
            'Libéria' => 'Africa/Monrovia',     
            'Líbia' => 'Africa/Tripoli',           
            'Madagáscar' => 'Indian/Antananarivo',
            'Malawi' => 'Africa/Blantyre',         
            'Mali' => 'Africa/Bamako',
            'Marrocos' => 'Africa/Casablanca',     
            'Mauritânia' => 'Africa/Nouakchott',
            'Maurícia' => 'Indian/Mauritius',
            'Moçambique' => 'Africa/Maputo',
            'Namíbia' => 'Africa/Windhoek',
            'Nigéria' => 'Africa/Lagos',
            'Níger' => 'Africa/Niamey',
            'Quénia' => 'Africa/Nairobi',
            'República Centro-Africana' => 'Africa/Bangui',
            'República Democrática do Congo' => 'Africa/Kinshasa',
            'República do Congo' => 'Africa/Brazzaville',
            'Ruanda' => 'Africa/Kigali',
            'Senegal' => 'Africa/Dakar',
            'Serra Leoa' => 'Africa/Freetown',
            'Seychelles' => 'Indian/Mahe',       
            'Somália' => 'Africa/Mogadishu',       
            'Suazilândia' => 'Africa/Mbabane',    
            'Sudão' => 'Africa/Khartoum',         
            'Sudão do Sul' => 'Africa/Juba',
            'São Tomé e Príncipe' => 'Africa/Sao_Tome',
            'Tanzânia' => 'Africa/Dar_es_Salaam',
            'Togo' => 'Africa/Lome',
            'Tunísia' => 'Africa/Tunis',
            'Uganda' => 'Africa/Kampala',
            'Zâmbia' => 'Africa/Lusaka',
            'Zimbabwe' => 'Africa/Harare',

            'Canadá' => 'America/Toronto',
            'Estados Unidos' => 'America/New_York',
            'México' => 'America/Mexico_City',

            'Antígua' => 'America/Antigua',
            'Bahamas' => 'America/Nassau',
            'Barbados' => 'America/Barbados',
            'Belize' => 'America/Belize',
            'Costa Rica' => 'America/Costa_Rica',
            'Cuba' => 'America/Havana',
            'Dominica' => 'America/Dominica',     
            'El Salvador' => 'America/El_Salvador',  
            'Granada' => 'America/Grenada',       
            'Guatemala' => 'America/Guatemala',       
            'Haiti' => 'America/Port-au-Prince',      
            'Honduras' => 'America/Tegucigalpa',
            'Jamaica' => 'America/Jamaica',
            'Nicarágua' => 'America/Managua',  
            'Panamá' => 'America/Panama',           
            'República Dominicana' => 'America/Santo_Domingo',
            'Santa Lúcia' => 'America/St_Lucia',      
            'São Cristóvão' => 'America/St_Kitts',   
            'São Vicente' => 'America/St_Vincent', 
            'Trinidade Tobago' => 'America/Port_of_Spain',

            'Argentina' => 'America/Argentina/Buenos_Aires',
            'Bolívia' => 'America/La_Paz',
            'Brasil' => 'America/Sao_Paulo',
            'Chile' => 'America/Santiago',
            'Colômbia' => 'America/Bogota',              
            'Equador' => 'America/Guayaquil',            
            'Guiana' => 'America/Guyana',                  
            'Paraguai' => 'America/Asuncion',              
            'Peru' => 'America/Lima',
            'Suriname' => 'America/Paramaribo',
            'Uruguai' => 'America/Montevideo',            
            'Venezuela' => 'America/Caracas',

            'Albânia' => 'Europe/Tirane',             
            'Alemanha' => 'Europe/Berlin',          
            'Andorra' => 'Europe/Andorra',           
            'Armênia' => 'Asia/Yerevan',             
            'Áustria' => 'Europe/Vienna',           
            'Azerbaijão' => 'Asia/Baku',          
            'Bielorrússia' => 'Europe/Minsk',
            'Bélgica' => 'Europe/Brussels',           
            'Bósnia-Herzegovina' => 'Europe/Sarajevo',
            'Bulgária' => 'Europe/Sofia',             
            'República Tcheca' => 'Europe/Prague',    
            'Cazaquistão' => 'Asia/Almaty',           
            'Chipre' => 'Asia/Nicosia',               
            'Croácia' => 'Europe/Zagreb',
            'Dinamarca' => 'Europe/Copenhagen',      
            'Eslováquia' => 'Europe/Bratislava',
            'Eslovênia' => 'Europe/Ljubljana',        
            'Espanha' => 'Europe/Madrid',
            'Estônia' => 'Europe/Tallinn',
            'Finlândia' => 'Europe/Helsinki',        
            'França' => 'Europe/Paris',
            'Grécia' => 'Europe/Athens',              
            'Geórgia' => 'Asia/Tbilisi',              
            'Hungria' => 'Europe/Budapest',          
            'Irlanda' => 'Europe/Dublin',
            'Islândia' => 'Atlantic/Reykjavik',      
            'Itália' => 'Europe/Rome',               
            'Letônia' => 'Europe/Riga',
            'Liechtenstein' => 'Europe/Vaduz',
            'Lituânia' => 'Europe/Vilnius',
            'Luxemburgo' => 'Europe/Luxembourg',    
            'República da Macedônia do Norte' => 'Europe/Skopje',
            'Malta' => 'Europe/Malta',                
            'Moldávia' => 'Europe/Chisinau',
            'Mônaco' => 'Europe/Monaco',             
            'Montenegro' => 'Europe/Podgorica',
            'Noruega' => 'Europe/Oslo',
            'Países Baixos' => 'Europe/Amsterdam',    
            'Polônia' => 'Europe/Warsaw',             
            'Portugal' => 'Europe/Lisbon',            
            'Reino Unido' => 'Europe/London',         
            'Romênia' => 'Europe/Bucharest',          
            'Rússia' => 'Europe/Moscow',              
            'Turquia' => 'Europe/Istanbul',         
            'San Marino' => 'Europe/San_Marino', 
            'Sérvia' => 'Europe/Belgrade',
            'Suécia' => 'Europe/Stockholm',           
            'Suíça' => 'Europe/Zurich',               
            'Ucrânia' => 'Europe/Kiev',               

            'Afeganistão' => 'Asia/Kabul',          
            'Arábia Saudita' => 'Asia/Riyadh',        
            'Azerbaijão' => 'Asia/Baku',
            'Bangladesh' => 'Asia/Dhaka',             
            'Barein' => 'Asia/Bahrain',               
            'Brunei' => 'Asia/Brunei',                
            'Butão' => 'Asia/Thimphu',               
            'Camboja' => 'Asia/Phnom_Penh',           
            'Cazaquistão' => 'Asia/Almaty',           
            'Catar' => 'Asia/Qatar',                  
            'China' => 'Asia/Shanghai',               
            'Cingapura' => 'Asia/Singapore',          
            'Coreia do Norte' => 'Asia/Pyongyang',
            'Coreia do Sul' => 'Asia/Seoul',          
            'Emirados Árabes Unidos' => 'Asia/Dubai', 
            'Filipinas' => 'Asia/Manila',
            'Iêmen' => 'Asia/Aden',                   
            'Índia' => 'Asia/Kolkata',               
            'Indonésia' => 'Asia/Jakarta',
            'Irã' => 'Asia/Tehran',                  
            'Iraque' => 'Asia/Baghdad',               
            'Israel' => 'Asia/Jerusalem',             
            'Japão' => 'Asia/Tokyo',                  
            'Jordânia' => 'Asia/Amman',               
            'Kuwait' => 'Asia/Kuwait',                
            'Laos' => 'Asia/Vientiane',              
            'Líbano' => 'Asia/Beirut',                
            'Malásia' => 'Asia/Kuala_Lumpur',         
            'Maldivas' => 'Indian/Maldives',         
            'Mianmar' => 'Asia/Yangon',               
            'Mongólia' => 'Asia/Ulaanbaatar',         
            'Nepal' => 'Asia/Kathmandu',              
            'Omã' => 'Asia/Muscat',                   
            'Paquistão' => 'Asia/Karachi',            
            'Quirguistão' => 'Asia/Bishkek',
            'Rússia' => 'Europe/Moscow',             
            'Síria' => 'Asia/Damascus',            
            'Sri Lanka' => 'Asia/Colombo',
            'Tailândia' => 'Asia/Bangkok',            
            'Tajiquistão' => 'Asia/Dushanbe',         
            'Timor Leste' => 'Asia/Dili',
            'Turcomenistão' => 'Asia/Ashgabat',       
            'Turquia' => 'Europe/Istanbul',           
            'Uzbequistão' => 'Asia/Tashkent',
            'Vietnã' => 'Asia/Ho_Chi_Minh',          

            'Austrália' => 'Australia/Canberra',          
            'Fiji' => 'Pacific/Suva', 
            'Ilhas Marshall' => 'Pacific/Majuro',
            'Ilhas Salomão' => 'Pacific/Honiara',
            'Kiribati' => 'Pacific/Tarawa',               
            'Micronésia' => 'Pacific/Pohnpei',           
            'Nauru' => 'Pacific/Nauru',                   
            'Nova Zelândia' => 'Pacific/Auckland',       
            'Palau' => 'Pacific/Koror',                   
            'Papua Nova Guiné' => 'Pacific/Port_Moresby', 
            'Samoa' => 'Pacific/Apia',
            'Tonga' => 'Pacific/Tongatapu',              
            'Tuvalu' => 'Pacific/Funafuti',
            'Vanuatu' => 'Pacific/Efate',
        ];
        
        if (isset($capitals[$country])) {
            $timezone = new DateTimeZone($capitals[$country]);
            $date = new DateTime('now', $timezone);
            $time = $date->format('H:i:s');
            return view('time')->with(['time' => $time, 'country' => $country]);
        } else {
            return view('time')->with('error', 'País não encontrado.');
        }
    }
}



